cat <<EOF > ansible/playbooks/create_vm.yml
---
- name: Deploy VM on vCenter
  hosts: vcenter
  gather_facts: no
  tasks:
    - name: Create VM from template
      community.vmware.vmware_guest:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
        datacenter: "<datacenter_name>"
        cluster: "<cluster_name>"
        folder: "<folder_name>"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        power_on: true
      vars_files:
        - vars.yml
EOF
